//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFTourApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string Where { get; set; }
        public System.DateTime TripDate { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    }
}
